### ISSUE TITLE
UX: Improve Accessibility

### ISSUE THREAD

**Issue by mathcrln** [mathcrln/jerry#9]
## Tasks
- [ ] Add focus ring on the Select Component (Dark Mode Switch)
- [ ] Add "Skip To Content" option
- [ ] Improve ring styling on various links & buttons
- [ ] Ensure that there are appropriate labels for each clickable item
